function rgb = ColorNameToRGB(colorName)
    % colorToRGB - Converts a color name string to its RGB triplet
    %
    % Usage:
    %   rgb = colorToRGB(colorName)
    %
    % Inputs:
    %   colorName - A string representing the color name
    %               (e.g., 'red', 'light red', 'dark blue')
    %
    % Outputs:
    %   rgb - A 1x3 vector representing the RGB triplet

    % Define a map of colors and their RGB values
    colors = containers.Map( ...
        { ...
            'red', 'light red', 'dark red', ...
            'green', 'light green', 'dark green', ...
            'blue', 'light blue', 'dark blue', ...
            'yellow', 'light yellow', 'dark yellow', ...
            'cyan', 'light cyan', 'dark cyan', ...
            'magenta', 'light magenta', 'dark magenta', ...
            'black', 'gray', 'dark gray', ...
            'orange', 'light orange', 'dark orange', ...
            'purple', 'light purple', 'dark purple', ...
            'pink', 'light pink', 'dark pink' ...
        }, ...
        { ...
            [1, 0, 0], [1, 0.5, 0.5], [0.6, 0, 0], ...
            [0, 1, 0], [0.5, 1, 0.5], [0, 0.6, 0], ...
            [0, 0, 1], [0.5, 0.5, 1], [0, 0, 0.6], ...
            [1, 1, 0], [1, 1, 0.5], [0.6, 0.6, 0], ...
            [0, 1, 1], [0.5, 1, 1], [0, 0.6, 0.6], ...
            [1, 0, 1], [1, 0.5, 1], [0.6, 0, 0.6], ...
            [0, 0, 0], [0.5, 0.5, 0.5], [0.3, 0.3, 0.3], ...
            [1, 0.5, 0], [1, 0.7, 0.4], [0.6, 0.3, 0], ...
            [0.5, 0, 0.5], [0.7, 0.4, 0.7], [0.3, 0, 0.3], ...
            [1, 0.75, 0.8], [1, 0.85, 0.9], [0.8, 0.5, 0.6] ...
        } ...
    );

    % Convert the input color name to lowercase for case-insensitive matching
    colorName = lower(colorName);

    % Check if the color exists in the map
    if colors.isKey(colorName)
        rgb = colors(colorName);
    else
        error('Color "%s" is not recognized. Please provide a valid color name.', colorName);
    end
end
