function colorName = RGBToColorName(rgb)
    % RGBToColorName - Finds the closest named color for an RGB triplet.
    %
    % Usage:
    %   colorName = RGBToColorName([R, G, B])
    %
    % Inputs:
    %   rgb - A 1x3 vector representing an RGB color.
    %
    % Outputs:
    %   colorName - A string with the closest color name.

    % Define the color map manually (copied from ColorToRGB.m)
    colorNames = { ...
        'Red', 'Light Red', 'Dark Red', ...
        'Green', 'Light Green', 'Dark Green', ...
        'Blue', 'Light Blue', 'Dark Blue', ...
        'Yellow', 'Light Yellow', 'Dark Yellow', ...
        'Cyan', 'Light Cyan', 'Dark Cyan', ...
        'Magenta', 'Light Magenta', 'Dark Magenta', ...
        'Black', 'Gray', 'Dark Gray', ...
        'Orange', 'Light Orange', 'Dark Orange', ...
        'Purple', 'Light Purple', 'Dark Purple', ...
        'Pink', 'Light Pink', 'Dark Pink' ...
    };

    colorValues = [ ...
        1, 0, 0; 1, 0.5, 0.5; 0.6, 0, 0; ...
        0, 1, 0; 0.5, 1, 0.5; 0, 0.6, 0; ...
        0, 0, 1; 0.5, 0.5, 1; 0, 0, 0.6; ...
        1, 1, 0; 1, 1, 0.5; 0.6, 0.6, 0; ...
        0, 1, 1; 0.5, 1, 1; 0, 0.6, 0.6; ...
        1, 0, 1; 1, 0.5, 1; 0.6, 0, 0.6; ...
        0, 0, 0; 0.5, 0.5, 0.5; 0.3, 0.3, 0.3; ...
        1, 0.5, 0; 1, 0.7, 0.4; 0.6, 0.3, 0; ...
        0.5, 0, 0.5; 0.7, 0.4, 0.7; 0.3, 0, 0.3; ...
        1, 0.75, 0.8; 1, 0.85, 0.9; 0.8, 0.5, 0.6 ...
    ];

    % Compute the Euclidean distance between input RGB and all stored colors
    distances = sqrt(sum((colorValues - rgb).^2, 2));

    % Find the closest matching color
    [~, idx] = min(distances);
    colorName = colorNames{idx};
end
