function imageFormats = GetImageFormatsMap()
    % GetImageFormatsMap - Returns a list of supported image formats.
    %
    % Outputs:
    %   imageFormats - A cell array containing file extensions and descriptions.

    imageFormats = { ...
        '*.png', 'PNG Image (*.png)'; ...
        '*.jpg', 'JPEG Image (*.jpg)'; ...
        '*.tiff', 'TIFF Image (*.tiff)'; ...
        '*.pdf', 'PDF Document (*.pdf)'; ...
        '*.eps', 'EPS File (*.eps)'; ...
        '*.fig', 'MATLAB Figure (*.fig)' ...
    };
end
